cookie:
  expiry_days: 1
  key: some_signature_key
  name: my-cockie
credentials:
  usernames:
    kubeops:
      email: aaaaa@bbbb.com
      failed_login_attempts: 0
      logged_in: false
      name: kubeops
      password: "Hashed-password"
pre-authorized:
  emails:
  - aaaaa@bbbb.com
